// Minimal ABIs for client-side contract interactions
// Full ABIs will be generated by rocketh-export

export const AFG_TOKEN_ABI = [
  { type: 'function', name: 'balanceOf', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'totalSupply', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'totalMined', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'currentRewardPerRound', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'deployedAt', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'ROUNDS_PER_HALVING', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'ROUND_DURATION', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'approve', inputs: [{ name: 'spender', type: 'address' }, { name: 'value', type: 'uint256' }], outputs: [{ type: 'bool' }], stateMutability: 'nonpayable' },
  { type: 'function', name: 'transfer', inputs: [{ name: 'to', type: 'address' }, { name: 'value', type: 'uint256' }], outputs: [{ type: 'bool' }], stateMutability: 'nonpayable' },
  // Admin
  { type: 'function', name: 'owner', inputs: [], outputs: [{ type: 'address' }], stateMutability: 'view' },
  { type: 'function', name: 'paused', inputs: [], outputs: [{ type: 'bool' }], stateMutability: 'view' },
  { type: 'function', name: 'pause', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'unpause', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'dexTaxBps', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'setDexTaxBps', inputs: [{ name: '_bps', type: 'uint256' }], outputs: [], stateMutability: 'nonpayable' },
] as const

export const AGENT_NFA_ABI = [
  { type: 'function', name: 'mint', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'payable' },
  { type: 'function', name: 'mintPrice', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'totalSupply', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'ownerOf', inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'address' }], stateMutability: 'view' },
  { type: 'function', name: 'getTraits', inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'tuple', components: [
    { name: 'intelligence', type: 'uint8' },
    { name: 'speed', type: 'uint8' },
    { name: 'specialization', type: 'uint8' },
    { name: 'talentRarity', type: 'uint8' },
  ]}], stateMutability: 'view' },
  { type: 'function', name: 'getStats', inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'tuple', components: [
    { name: 'xp', type: 'uint64' },
    { name: 'level', type: 'uint8' },
    { name: 'problemsSolved', type: 'uint32' },
    { name: 'problemsAttempted', type: 'uint32' },
    { name: 'mintedAt', type: 'uint64' },
  ]}], stateMutability: 'view' },
  { type: 'function', name: 'getTier', inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'uint8' }], stateMutability: 'view' },
  { type: 'function', name: 'getLevel', inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'uint8' }], stateMutability: 'view' },
  { type: 'function', name: 'experience', inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'string' }], stateMutability: 'view' },
  { type: 'function', name: 'isEligible', inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'bool' }], stateMutability: 'view' },
  { type: 'function', name: 'tokenURI', inputs: [{ name: 'tokenId', type: 'uint256' }], outputs: [{ type: 'string' }], stateMutability: 'view' },
  { type: 'event', name: 'AgentMinted', inputs: [
    { name: 'tokenId', type: 'uint256', indexed: true },
    { name: 'to', type: 'address', indexed: true },
    { name: 'intelligence', type: 'uint8', indexed: false },
    { name: 'speed', type: 'uint8', indexed: false },
    { name: 'specialization', type: 'uint8', indexed: false },
    { name: 'talentRarity', type: 'uint8', indexed: false },
  ]},
  // Admin
  { type: 'function', name: 'owner', inputs: [], outputs: [{ type: 'address' }], stateMutability: 'view' },
  { type: 'function', name: 'paused', inputs: [], outputs: [{ type: 'bool' }], stateMutability: 'view' },
  { type: 'function', name: 'pause', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'unpause', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'setMintPrice', inputs: [{ name: '_price', type: 'uint256' }], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'withdraw', inputs: [], outputs: [], stateMutability: 'nonpayable' },
] as const

export const PROBLEM_MANAGER_ABI = [
  { type: 'function', name: 'problemCount', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'getProblem', inputs: [{ name: 'problemId', type: 'uint256' }], outputs: [{ type: 'tuple', components: [
    { name: 'questionHash', type: 'bytes32' },
    { name: 'createdAt', type: 'uint64' },
    { name: 'deadline', type: 'uint64' },
    { name: 'resolved', type: 'bool' },
    { name: 'correctAnswerHash', type: 'bytes32' },
  ]}], stateMutability: 'view' },
  { type: 'function', name: 'getPhase', inputs: [{ name: 'problemId', type: 'uint256' }], outputs: [{ type: 'uint8' }], stateMutability: 'view' },
  { type: 'function', name: 'isActive', inputs: [{ name: 'problemId', type: 'uint256' }], outputs: [{ type: 'bool' }], stateMutability: 'view' },
  // Admin
  { type: 'function', name: 'owner', inputs: [], outputs: [{ type: 'address' }], stateMutability: 'view' },
  { type: 'function', name: 'paused', inputs: [], outputs: [{ type: 'bool' }], stateMutability: 'view' },
  { type: 'function', name: 'pause', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'unpause', inputs: [], outputs: [], stateMutability: 'nonpayable' },
] as const

export const REWARD_DISTRIBUTOR_ABI = [
  { type: 'function', name: 'pendingRewards', inputs: [{ name: 'account', type: 'address' }], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'claimRewards', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'totalDistributed', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'event', name: 'RewardsClaimed', inputs: [
    { name: 'account', type: 'address', indexed: true },
    { name: 'amount', type: 'uint256', indexed: false },
  ]},
  // Admin
  { type: 'function', name: 'owner', inputs: [], outputs: [{ type: 'address' }], stateMutability: 'view' },
  { type: 'function', name: 'paused', inputs: [], outputs: [{ type: 'bool' }], stateMutability: 'view' },
  { type: 'function', name: 'pause', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'unpause', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'devWallet', inputs: [], outputs: [{ type: 'address' }], stateMutability: 'view' },
  { type: 'function', name: 'setDevWallet', inputs: [{ name: '_wallet', type: 'address' }], outputs: [], stateMutability: 'nonpayable' },
] as const
